- name: Install redis repo
  ansible.builtin.yum:  # this is the module to install redis
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: true # while configuring redis server from ansible server with remote access then enable to true.     

- name: Enable redis 6.2
  ansible.builtin.command: yum module enable redis:remi-6.2 -y

- name: Install redis
  ansible.builtin.yum:
    name: redis
    state: installed
      
- name: Allow remote connection to redis server
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start and enable redis
  ansible.builtin.service:
    name: redis
    state: started
    enabled: yes