- name: copy {{component}} service
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

# it will restart and reload the service
- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart {{component}}
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted

    
  